# Generated by Django 4.1.6 on 2023-02-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copycat', '0002_remove_mp4file_text_mp4file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp4file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='mp4file',
            name='file',
            field=models.FileField(upload_to='mp4file/'),
        ),
    ]
