# Generated by Django 4.1.6 on 2023-02-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copycat', '0003_mp4file_image_alter_mp4file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadmp4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.DeleteModel(
            name='Mp4file',
        ),
    ]
