# Generated by Django 4.1.6 on 2023-02-08 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copycat', '0004_uploadmp4_delete_mp4file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uploadmp4',
        ),
    ]
