# Generated by Django 4.1.6 on 2023-02-13 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copycat', '0008_uploadmp4_created_at_uploadmp4_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmp4',
            name='updated_at',
        ),
    ]
