# Generated by Django 4.1.6 on 2023-02-13 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copycat', '0009_remove_uploadmp4_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmp4',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploadmp4',
            name='files',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='uploadmp4',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploadmp4',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
